# -*- coding: utf-8 -*-
"""
工具包 - 聚合所有工具的 Schema 定义和调度表
"""
from tools.file_ops import SCHEMAS as FILE_OPS_SCHEMAS, TOOL_DISPATCH as FILE_OPS_DISPATCH
from tools.search import SCHEMAS as SEARCH_SCHEMAS, TOOL_DISPATCH as SEARCH_DISPATCH
from tools.execution import SCHEMAS as EXECUTION_SCHEMAS, TOOL_DISPATCH as EXECUTION_DISPATCH
from tools.analysis import SCHEMAS as ANALYSIS_SCHEMAS, TOOL_DISPATCH as ANALYSIS_DISPATCH
from tools.git_ops import SCHEMAS as GIT_SCHEMAS, TOOL_DISPATCH as GIT_DISPATCH

# 聚合所有工具Schema（OpenAI function calling格式）
TOOLS = FILE_OPS_SCHEMAS + SEARCH_SCHEMAS + EXECUTION_SCHEMAS + ANALYSIS_SCHEMAS + GIT_SCHEMAS

# 聚合所有工具调度表
TOOL_DISPATCH = {}
TOOL_DISPATCH.update(FILE_OPS_DISPATCH)
TOOL_DISPATCH.update(SEARCH_DISPATCH)
TOOL_DISPATCH.update(EXECUTION_DISPATCH)
TOOL_DISPATCH.update(ANALYSIS_DISPATCH)
TOOL_DISPATCH.update(GIT_DISPATCH)
